extends: 'eslint:recommended'
env:
  node: true
  commonjs: true
  es6: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  no-extra-semi:
    - error
