sudo: required
dist: trusty
language: node_js
node_js:
  - "7"

addons:
#  firefox: "38.0"
  apt:
    sources:
      # needed to install g++ that is used by npms's native modules
      - ubuntu-toolchain-r-test
    packages:
      # needed to install g++ that is used by npms's native modules
      - g++-4.8

branches:
  except:
    - g3

cache:
  yarn: true
  directories:
     - ./node_modules
     - ./.chrome/chromium
     - ./aio/node_modules

env:
    - EMBER_VERSION=default
    - EMBER_VERSION=release
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_VERSION=release
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

before_install:
    - "npm config set spin false"
    - "npm install -g npm@^2"

install:
    - npm install -g bower
    - npm install
    - bower install

script:
    - ember test --server
